# These are all the cops that are enabled in the default configuration.

# By default, the rails cops are not run. Override in project or home
# directory .rubocop.yml files, or by giving the -R/--rails option.
Rails:
  Enabled: true

Lint/HandleExceptions:
  Enabled: true
  Exclude:
    - bin/*
